const franceProivinces = [
  "Île-de-France",
  "Berry",
  "Orléanais",
  "Normandy",
  "Languedoc",
  "Lyonnais",
  "Dauphiné",
  "Champagne",
  "Aunis",
  "Saintonge",
  "Poitou",
  "Guyenne and Gascony",
  "Burgundy",
  "Picardy",
  "Anjou",
  "Provence",
  "Angoumois",
  "Bourbonnais",
  "Marche",
  "Brittany",
  "Maine",
  "Touraine",
  "Limousin",
  "Foix",
  "Auvergne",
  "Béarn",
  "Alsace",
  "Artois",
  "Roussillon",
  "Flanders and Hainaut",
  "Franche-Comté",
  "Lorraine",
  "Corsica",
  "Nivernais"
];
